### ISSUE TITLE
Create "plus button" to Test activity.

### ISSUE THREAD

**Issue by kaarel95** [RainVagel/Health-Reporter-Android#40]
Plus button lets user to add a test to the Test Activity tests' list or add a new divider.
[See TEST requirement](https://github.com/RainVagel/Health-Reporter-Android/wiki/Functional-requirements)
Estimated work hours: 5-6 hours

**Comment by lubja** [comment]
Turned out to be obsolete.

**Comment by lubja** [comment]
Turned out to be obsolete.
